# Generated by Django 5.1.1 on 2024-10-07 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
           name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                # outros campos...
            ],
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=255)),
                ('duvida', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Duvidas',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.duvida')),
            ],
        ),
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id_investidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investidores',
            },
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('avaliacao', models.FloatField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Corretoras',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('relato_feedback', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='PerfilInvest',
            fields=[
                ('idperfilinvest', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_capitalinvest', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Perfis de Investimento',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Seguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dicas', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Seguranças',
            },
        ),
        migrations.CreateModel(
            name='TipoInvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_investimento', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('relato', models.TextField()),
                ('dicas', models.TextField()),
                ('investidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.investidor')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Investimentos',
            },
        ),
    ]
