# Generated by Django 5.1.1 on 2024-10-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241011_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investidor',
            name='senha',
        ),
    ]
